[package]
name = "rs-backend"
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
nalgebra = "0.32.3"
octocrab = "0.30.1"
tokio = { version = "1", features = ["full"] }
